SELECT DEPTADDR FROM DEPT WHERE DEPTNAME = 'SALES';
SELECT * FROM DEPT WHERE DEPTADDR IN ('NEW YORK', 'CHICAGO');
SELECT MIN(SALVALUE) AS MINSALARY2007 FROM SALARY WHERE YEAR = 2007;
SELECT * FROM EMP WHERE BIRTHDATE <= to_date('01-01-1960','dd-mm-yyyy');
SELECT COUNT(*) FROM EMP;
SELECT RTRIM(LOWER(EMPNAME), 't') AS NEWEMPNAME FROM EMP WHERE EMPNAME NOT LIKE('% %');
SELECT EMPNO, EMPNAME, TO_CHAR(BIRTHDATE, 'DD-MONTH-YYYY','NLS_DATE_LANGUAGE = AMERICAN') FROM EMP
SELECT EMPNO, EMPNAME, TO_CHAR(BIRTHDATE, 'DD-MONTH-YEAR','NLS_DATE_LANGUAGE = AMERICAN') FROM EMP
SELECT DECODE(JOBNAME, 'DRIVER', 'WORKER', 'CLERK', 'WORKER', JOBNAME) AS NEWJOB FROM JOB;--DECODE
SELECT YEAR, AVG(SALVALUE) FROM SALARY GROUP BY YEAR HAVING COUNT(MONTH) >= 3;
SELECT EMP.EMPNAME, SALARY.MONTH,  SALARY.SALVALUE FROM EMP, SALARY WHERE EMP.EMPNO = SALARY.EMPNO;
SELECT EMP.EMPNAME, JOB.JOBNAME, SALARY.SALVALUE, JOB.MINSALARY
    FROM SALARY INNER JOIN EMP ON SALARY.EMPNO = EMP.EMPNO INNER JOIN CAREER ON CAREER.EMPNO = EMP.EMPNO INNER JOIN JOB ON JOB.JOBNO = CAREER.JOBNO
    WHERE SALARY.SALVALUE > JOB.MINSALARY AND SALARY.SALVALUE < JOB.MINSALARY + 500
SELECT E.EMPNAME, S.SALVALUE, J.MINSALARY, J.JOBNAME FROM SALARY S INNER JOIN EMP E ON (S.EMPNO = E.EMPNO) INNER JOIN CAREER C ON (E.EMPNO = C.EMPNO) INNER JOIN JOB J ON (C.JOBNO = J.JOBNO) WHERE S.SALVALUE = J.MINSALARY;
SELECT E.EMPNAME, C.STARTDATE, C.ENDDATE FROM EMP E NATURAL JOIN CAREER C;
SELECT E.EMPNAME, C.STARTDATE, C.ENDDATE FROM EMP E INNER JOIN CAREER C ON (E.EMPNO = C.EMPNO);
SELECT E.EMPNAME, D.DEPTNAME, J.JOBNAME, C.STARTDATE, C.ENDDATE FROM EMP E NATURAL JOIN CAREER C NATURAL JOIN DEPT D NATURAL JOIN JOB J ORDER BY E.EMPNAME, C.STARTDATE;
SELECT EMPNAME, STARTDATE, ENDDATE
    FROM EMP, CAREER
    WHERE EMP.EMPNO = CAREER.EMPNO (+)
ORDER BY EMP.EMPNAME, CAREER.STARTDATE;
